<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="GamePath.props" Condition="Exists('GamePath.props')" />
    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyName>StreamSideResearch</AssemblyName>
        <AssemblyVersion>2.0.0</AssemblyVersion>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <!-- <DefineConstants>IN_TEST_MODE</DefineConstants> -->
        <IsPackable>false</IsPackable>
        <LangVersion>latest</LangVersion>
        <NeutralLanguage>en-US</NeutralLanguage>
        <PlatformTarget>x64</PlatformTarget>
        <RootNamespace>StreamSideResearch</RootNamespace>
        <TargetFramework>net6.0</TargetFramework>
        <TargetName>$(AssemblyName)-$(AssemblyVersion)</TargetName>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="$(MelonLoaderDir)\net6\0Harmony.dll" Private="false" />
        <Reference Include="$(MelonLoaderDir)\net6\MelonLoader.dll" Private="false" />
        <Reference Include="$(MelonLoaderDir)\net6\Il2CppInterop.Runtime.dll" Private="false" />
        <Reference Include="$(Il2CppDir)\Assembly-CSharp.dll" Private="false" />
        <Reference Include="$(Il2CppDir)\Il2CppFusion.Runtime.dll" Private="false" />
        <Reference Include="$(Il2CppDir)\Il2Cppmscorlib.dll" Private="false" />
        <Reference Include="$(Il2CppDir)\Il2CppWallyBox.dll" Private="false" />
        <Reference Include="$(Il2CppDir)\Unity.TextMeshPro.dll" Private="false" />
        <Reference Include="$(Il2CppDir)\UnityEngine.AIModule.dll" Private="false" />
        <Reference Include="$(Il2CppDir)\UnityEngine.AnimationModule.dll" Private="false" />
        <Reference Include="$(Il2CppDir)\UnityEngine.CoreModule.dll" Private="false" />
        <Reference Include="$(Il2CppDir)\UnityEngine.InputLegacyModule.dll" Private="false" />
        <Reference Include="$(Il2CppDir)\UnityEngine.UI.dll" Private="false" />
        <Reference Include="$(Il2CppDir)\UnityEngine.UIModule.dll" Private="false" />
        <PackageReference Include="Costura.Fody" Version="6.0.0">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="TwitchLib" Version="3.5.3" Private="false" />
    </ItemGroup>
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(BaseGameDir)\Mods&quot;" />
    </Target>
</Project>
